/** Editorial chapters already told on the heritage journey. */
export const JOURNAL = [
  {
    n: "01",
    category: "Heritage",
    title: "A Royal Vision",
    date: "1912",
    summary: "Maharaja Nalwadi Krishnaraja Wadiyar IV established the Mysore silk weaving factory in Mysuru.",
    image: "/heritage/01-wide.jpg?v=5",
    href: "/heritage?chapter=1",
    related: { href: "/sarees", label: "Discover the collection" },
  },
  {
    n: "02",
    category: "Craft",
    title: "Before the Saree, the Silk",
    date: "1785",
    summary: "Sericulture was established at Channapatna in 1785, during the reign of Tipu Sultan.",
    image: "/heritage/02.jpg?v=4",
    href: "/heritage?chapter=2",
    related: { href: "/sarees?category=pure-silk", label: "Shop pure silk" },
  },
  {
    n: "03",
    category: "Craft",
    title: "Knowledge Became Craft",
    date: "The Artisan",
    summary: "The Tata Silk Farm in Bengaluru trained a generation in sericulture, processing, and weaving.",
    image: "/heritage/03.jpg?v=4",
    href: "/heritage?chapter=3",
    related: { href: "/story", label: "Read our story" },
  },
  {
    n: "04",
    category: "Silk Stories",
    title: "The Signature of Mysore",
    date: "Zari",
    summary: "Traditional Mysore Silk zari is 65% pure silver and 0.65% gold — a quiet glow, not loud ornament.",
    image: "/heritage/04.jpg?v=4",
    href: "/heritage?chapter=4",
    related: { href: "/sarees", label: "Discover the collection" },
  },
  {
    n: "05",
    category: "Heritage",
    title: "Woven for Royalty",
    date: "Royalty",
    summary: "The earliest Mysore silk was made for the royal family and the Wadiyar court.",
    image: "/heritage/05.jpg?v=4",
    href: "/heritage?chapter=5",
    related: { href: "/collections", label: "Explore collections" },
  },
  {
    n: "06",
    category: "KSIC Stories",
    title: "Mysuru to the World",
    date: "Recognised",
    summary: "The Geographical Indication protects Mysore Silk as a regional identity admired beyond Karnataka.",
    image: "/heritage/06.jpg?v=3",
    href: "/heritage?chapter=6",
    related: { href: "/collections", label: "Explore collections" },
  },
  {
    n: "07",
    category: "KSIC Stories",
    title: "A Legacy That Endures",
    date: "KSIC",
    summary: "Through KSIC, every saree still carries its own identity and the legacy behind the name.",
    image: "/heritage/07.jpg?v=3",
    href: "/heritage?chapter=7",
    related: { href: "/your-saree", label: "Build your saree" },
  },
] as const;

export const CARE_NOTES = [
  {
    title: "Washing",
    body: "Dry clean only. Do not soak Mysore silk at home or use household detergent.",
  },
  {
    title: "Drying",
    body: "After a wearing, air the saree in shade. Keep it away from direct sun, which dulls both silk and zari.",
  },
  {
    title: "Ironing",
    body: "Iron on the reverse, on a low silk setting, with a cotton cloth between the iron and the zari.",
  },
  {
    title: "Folding",
    body: "Refold along fresh lines so the zari border does not crack in the same place.",
  },
  {
    title: "Storage",
    body: "Store folded in muslin, not plastic. Give the saree air before it returns to the wardrobe.",
  },
  {
    title: "Zari care",
    body: "Keep gold zari from moisture, perfume, and friction against jewellery.",
  },
] as const;
